=== salimb/genesis/dist/target/dist/genesis/engine/schemas/rack.xsd
<?xml version="1.0"?>
<xs:schema targetNamespace="http://genesis.uk.com/schemas/1.0/genesis-root"
           elementFormDefault="qualified" attributeFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:genesis="http://genesis.uk.com/schemas/1.0/genesis-root">
    <xs:annotation>
        <xs:documentation>
      The Rack schema file defines the valid elements and their types
      for instances of rack.xml files. 
      The elements are defined first followed by their types.
      HOOS: I understand that this approach is a little like defining an
      interface whose implementation may change, TBC.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="Rack" type="genesis:RackType"/>
    <xs:complexType name="RackType">
        <xs:annotation>
            <xs:documentation>The root element for a rack configuration file.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="Dimensions" type="genesis:DimensionsType" />
            <xs:element name="UnitCapacity" type="genesis:UnitCapacityType" />
            <xs:element name="GridLocation" type="genesis:GridLocationType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DimensionsType">
        <xs:annotation>
            <xs:documentation>Used to store the dimensions of the rack.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="DimensionX" type="genesis:DimensionType" />
            <xs:element name="DimensionY" type="genesis:DimensionType" />
            <xs:element name="DimensionZ" type="genesis:DimensionType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DimensionType">
        <xs:annotation>
            <xs:documentation>A positive integer with units.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="units" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="UnitCapacityType">
        <xs:annotation>
            <xs:documentation>A positive integer.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger"/>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="GridLocationType">
        <xs:annotation>
            <xs:documentation>The grid location of the rack.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="XCoordinate" type="xs:integer" />
            <xs:element name="YCoordinate" type="xs:integer" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== salimb/genesis/dist/target/dist/genesis/config/MyEnterprise/physical/MyDatacentre/MyRack/rack.xml
<Rack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://genesis.uk.com/schemas/1.0/genesis-root"
      xsi:schemaLocation="http://genesis.uk.com/schemas/1.0/genesis-root engine/schemas/rack.xsd">
  <Name>MyRack</Name>
  <Dimensions>
    <DimensionX units="mm">1000</DimensionX>
    <DimensionY units="mm">1000</DimensionY>
    <DimensionZ units="mm">1000</DimensionZ>
  </Dimensions>
  <UnitCapacity>42</UnitCapacity>
  <GridLocation>
    <XCoordinate>0</XCoordinate>
    <YCoordinate>0</YCoordinate>
  </GridLocation>
</Rack>
