=== salimb/genesis/dist/src/main/root-files/engine/schemas/genesis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://genesis.uk.com/schemas/1.0/genesis-root" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:genesis="http://genesis.uk.com/schemas/1.0/genesis-root">
    <xs:element name="genesis">
        <xs:annotation>
            <xs:documentation>The root element for a genesis configuration file.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element ref="genesis:model" />
            </xs:all>
        </xs:complexType>
    </xs:element>
  
  <!-- The model element -->
    <xs:element name="model" type="genesis:ModelType">
        <xs:annotation>
            <xs:documentation>The model that Genesis should be working from.</xs:documentation>
        </xs:annotation>
    </xs:element>
  
  <!-- The model type -->
    <xs:complexType name="ModelType">
        <xs:sequence>
            <xs:element ref="genesis:object" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    
    <!-- Reader that can interpret the model -->
        <xs:attribute name="reader" type="xs:string" use="required" />
    </xs:complexType>
  
  <!-- The object element -->
    <xs:element name="object" type="genesis:ObjectType">
        <xs:annotation>
            <xs:documentation>An object that can be configured within Genesis.</xs:documentation>
        </xs:annotation>
    </xs:element>
  
  <!-- The declaration of an object -->
    <xs:complexType name="ObjectType">
        <xs:sequence>
      <!-- Any executable actions -->
            <xs:element name="action" type="genesis:ActionType" minOccurs="0" maxOccurs="unbounded" />
      
       <!-- Any child objects  -->
            <xs:element ref="genesis:object" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>  
  
    <!-- Name of the object -->
        <xs:attribute name="name" type="xs:string" use="required">
        </xs:attribute>
    </xs:complexType>

  <!-- An action that can be performed on an object -->
    <xs:complexType name="ActionType">
    <!-- The name of the action -->
        <xs:attribute name="name" type="xs:string" use="required" />
    
    <!-- The class that can handle the actions -->
        <xs:attribute name="handler" type="xs:string" use="required" />
    
    <!-- The other actions that need to be performed to make this action work -->
        <xs:attribute name="depends" type="xs:string" use="optional" />
    </xs:complexType>
</xs:schema>

=== salimb/genesis/model/src/test/etc/genesis-structured.xml
<?xml version="1.0" encoding="UTF-8"?>
<genesis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xmlns="http://genesis.uk.com/schemas/1.0/genesis-root" 
                xmlns:fsmodel="http://genesis.uk.com/schemas/1.0/genesis-fs-model"
                xsi:schemaLocation="http://genesis.uk.com/schemas/1.0/genesis-root system/genesis.xsd http://genesis.uk.com/schemas/1.0/genesis-fs-model system/genesis-fs-model.xsd">
  <!-- The model that is being used by this Genesis instance -->
  <model reader="com.uk.genesis.model.FileSystemModelReader">
    <!-- Declare the location of the global xml -->
    <fsmodel:global filename="config/common.xml" />
  
    <!-- Declare the model using Genesis XML extensions namespace -->
    <fsmodel:object name="Enterprise" path="config/${name}" filename="enterprise.xml">
      <fsmodel:object name="Datacentre" path="physical/${name}" filename="datacentre.xml">
        <fsmodel:object name="Rack" path="${name}" filename="rack.xml">
          <fsmodel:object name="Node-00" filename="node-00-${name}.xml" />
          <fsmodel:object name="Node-01" filename="node-01-${name}.xml" />
          <fsmodel:object name="Node-02" filename="node-02-${name}.xml" />
        </fsmodel:object>
      </fsmodel:object>

      <fsmodel:object name="Service" path="logical/${name}" filename="programme.xml">
        <fsmodel:object name="Environment" path="${name}" filename="environment.xml">
          <fsmodel:object name="Application" path="${name}" filename="application.xml">
            <!-- You can package and deploy an application -->
            <action name="package" handler="com.uk.genesis.actions.XmlArchetypePackager" />
            <action name="deploy" handler="com.uk.genesis.actions.XmlArchetypeDeployer" depends="package" />
          </fsmodel:object>
        </fsmodel:object>
      </fsmodel:object>
    </fsmodel:object>
  </model>
</genesis>

=== salimb/genesis/model/src/test/etc/genesis-xml-structured.xml
<?xml version="1.0" encoding="UTF-8"?>
<genesis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xmlns="http://genesis.uk.com/schemas/1.0/genesis-root" 
                xmlns:xmodel="http://genesis.uk.com/schemas/1.0/genesis-xml-model"
                xsi:schemaLocation="http://genesis.uk.com/schemas/1.0/genesis-root system/genesis.xsd http://genesis.uk.com/schemas/1.0/genesis-xml-model system/genesis-xml-model.xsd">
  <!-- The model that is being used by this Genesis instance -->
  <model reader="com.uk.genesis.model.XmlModelReader">
    <!-- Declare the location of the global properties -->
    <xmodel:global filename="config/common.xml" />
  
    <!-- Declare the model using Genesis XML extensions namespace -->
    <xmodel:object name="Enterprise" path="config/${name}" schema="schemas/enterprise.xsd" filename="enterprise.xml">
      <xmodel:object name="Datacentre" path="physical/${name}" schema="schemas/datacentre.xsd" filename="datacentre.xml">
        <xmodel:object name="Rack" path="${name}" schema="schemas/rack.xsd" filename="rack.xml">
          <xmodel:object name="Server" schema="schemas/server.xsd" filename="server-${name}.xml" />
          <xmodel:object name="Firewall" schema="schemas/firewall.xsd" filename="firewall-${name}.xml" />
          <xmodel:object name="Hub" schema="schemas/hub.xsd" filename="hub-${name}.xml" />
        </xmodel:object>
      </xmodel:object>

      <xmodel:object name="Service" path="logical/${name}" schema="schemas/service.xsd" filename="programme.xml">
        <xmodel:object name="Environment" path="${name}" schema="schemas/environment.xsd" filename="environment.xml">
          <xmodel:object name="Application" path="${name}" schema="schemas/application.xsd" filename="application.xml" />
        </xmodel:object>
      </xmodel:object>
    </xmodel:object>
  </model>
</genesis>
